trigger:
- main
pool:
  vmImage: 'Ubuntu-latest'
variables:
  acrserviceconnection: credpay-acr
  tag: '$(Build.BuildId)'
  frontendrepo: 'credpay/frontend'
  paymentrepo: 'credpay/paymemt'
  userrepo: 'credpay/user'
stages:
  - stage: DockerBuild
    displayName: Build Docker Images
    jobs:
      - job: BuildandpushImages
        displayName: Build Docker Images
        steps:
        - checkout: self
        - task: Docker@2
          inputs:
            containerRegistry: 'credpay-acr'
            repository: '$(frontendrepo)'
            command: 'buildAndPush'
            Dockerfile: 'frontend-react/Dockerfile'
            buildContext: frontend-react
            tags: |
              $(tag)
              latest
        - task: Docker@2
          inputs:
            containerRegistry: 'credpay-acr'
            repository: '$(paymentrepo)'
            command: 'buildAndPush'
            Dockerfile: 'payment-service/Dockerfile'
            buildContext: payment-service
            tags: |
              $(tag)
              latest
        - task: Docker@2
          inputs:
            containerRegistry: 'credpay-acr'
            repository: '$(userrepo)'
            command: 'buildAndPush'
            Dockerfile: 'user-service/Dockerfile'
            buildContext: user-service
            tags: |
              $(tag)
              latest
